# https://medium.com/statuscode/dockerising-a-node-js-and-mongodb-app-d22047e2806f
version: "1"
services:
  app:
    container_name: book
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - personadb
  personadb:
    container_name: personadb
    image: personadb
    volumes:
      - ./khaiphong:/khaiphong/personadb
    ports:
      - "27017:27017"

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # share port 8081 via a load-balanced network called webnet
    ports:
      - "8081:8081"
    networks:
      - webnet
# use default webnet settings (which is a load-balanced overlay network)
networks:
  webnet:
